### ISSUE TITLE
解绑功能初步开发以及后续的开发讨论

### ISSUE THREAD

**Issue by TonyHappyStyle** [wjdh-platform/wjdh-platform-api-document#10]
1.以前我们已经开发过一次解绑功能，那时候是直接删除用户的绑定记录，但是现在，需要经过安防平台的审核，在审核过程中与公安平台数据同步。所以这次点击解绑后，是需要经过一段时间的审核状态。

**Comment by KKMAMi** [comment]
[test](https://developers.weixin.qq.com/miniprogram/dev/framework/quickstart/code.html#JSON-%E9%85%8D%E7%BD%AE)

**Comment by KKMAMi** [comment]
- [项目导入或新建](#项目导入或新建)
    - [初次使用需下载微信开发者工具](#初次使用需下载微信开发者工具)
  - [项目新建](#项目新建)
    - [新建项目选择小程序项目，选择代码存放的硬盘路径，填入申请到的小程序的 AppID，给你的项目起一个好听的名字，勾选 "不使用云服务" （注意: 你要选择一个空的目录才可以创建项目），点击新建，你就得到了你的第一个小程序了，点击顶部菜单编译就可以在微信开发者工具中预览你的第一个小程序。](#新建项目选择小程序项目选择代码存放的硬盘路径填入申请到的小程序的-appid给你的项目起一个好听的名字勾选-不使用云服务-注意-你要选择一个空的目录才可以创建项目点击新建你就得到了你的第一个小程序了点击顶部菜单编译就可以在微信开发者工具中预览你的第一个小程序)
    - [点击工具上的编译按钮，可以在工具的左侧模拟器界面看到这个小程序的表现，也可以点击预览按钮，通过微信的扫一扫在手机上体验你的第一个小程序。](#点击工具上的编译按钮可以在工具的左侧模拟器界面看到这个小程序的表现也可以点击预览按钮通过微信的扫一扫在手机上体验你的第一个小程序)
  - [项目导入](#项目导入)
  - [.json 后缀的 JSON 配置文件](#json-后缀的-json-配置文件)
  - [.wxml 后缀的 WXML 模板文件](#wxml-后缀的-wxml-模板文件)
  - [.wxss 后缀的 WXSS 样式文件](#wxss-后缀的-wxss-样式文件)
  - [.js 后缀的 JS 脚本逻辑文件](#js-后缀的-js-脚本逻辑文件)
# 项目导入或新建
### 初次使用需下载[微信开发者工具](https://developers.weixin.qq.com/miniprogram/dev/devtools/download.html)  
## 项目新建
### 新建项目选择小程序项目，选择代码存放的硬盘路径，填入申请到的小程序的 AppID，给你的项目起一个好听的名字，勾选 "不使用云服务" （注意: 你要选择一个空的目录才可以创建项目），点击新建，你就得到了你的第一个小程序了，点击顶部菜单编译就可以在微信开发者工具中预览你的第一个小程序。
### 点击工具上的编译按钮，可以在工具的左侧模拟器界面看到这个小程序的表现，也可以点击预览按钮，通过微信的扫一扫在手机上体验你的第一个小程序。
![avatar](https://res.wx.qq.com/wxdoc/dist/assets/img/first-program.2ee81a52.png)

## 项目导入

 [小程序代码构成](https://developers.weixin.qq.com/miniprogram/dev/framework/quickstart/code.html#JSON-%E9%85%8D%E7%BD%AE)
## .json 后缀的 JSON 配置文件
## .wxml 后缀的 WXML 模板文件
## .wxss 后缀的 WXSS 样式文件
## .js 后缀的 JS 脚本逻辑文件

**Comment by TonyHappyStyle** [comment]
@KKMAMi 
解绑业主时，该房屋下的其他成员将一起被解绑。
希望安防平台这边也按照相同逻辑处理 @mgsq
