### ISSUE TITLE
房屋详情页面返回家属在管理员上面

### ISSUE THREAD

**Issue by KKMAMi** [wjdh-platform/wjdh-platform-api-document#11]

**Comment by KKMAMi** [comment]
@TonyHappyStyle

**Comment by KKMAMi** [comment]
![WechatIMG185](https://user-images.githubusercontent.com/37092331/103327075-07b44c00-4a8e-11eb-80ff-444df30d19b0.png)
![WechatIMG186](https://user-images.githubusercontent.com/37092331/103327079-0edb5a00-4a8e-11eb-88e7-6f2ffe2c30a4.jpeg)

**Comment by KKMAMi** [comment]
房屋列表点击解绑成功后 刷新列表时候应该返回解绑审核中的提示

**Comment by KKMAMi** [comment]
房屋详情的已绑定列表，解绑家属时，刷新详情数据应该返回类似解绑中字样

**Comment by TonyHappyStyle** [comment]
已完成，请拉取文档 @KKMAMi
