### ISSUE TITLE
房屋列表数据展示

### ISSUE THREAD

**Issue by KKMAMi** [wjdh-platform/wjdh-platform-api-document#16]
房屋列表的参数只有type，切换小区后列表展示没有区分
![bug](https://user-images.githubusercontent.com/37092331/103601125-f367c780-4f43-11eb-983c-65cb130f3a77.jpeg)

**Comment by KKMAMi** [comment]
账单列表传了小区的标识 当前是碧桂园小区 返回的还是全部小气的账单列表

**Comment by KKMAMi** [comment]
@TonyHappyStyle

**Comment by TonyHappyStyle** [comment]
# 携带值中已添加小区唯一编号

### 4.1.2账单列表

>说明:获得该用户的所有账单

>请求方法：POST

>url地址：<https://tc.mg.cool/api/v1/payments/list>

#### 4.1.2.1头部信息

> Authorization: Bearer token值

#### 4.1.2.2携带数据

字段|类型|是否必填|释义|选项
|:--|:--|:--|:--|:--
paied|boolean|选填|订单状态0待支付1已支付|
title|string|选填|订单名称|如“物业费”（初始化时提供）
house_id|integer|选填|房屋id|只查看某房屋的订单
per_page|integer|选填|每页显示多少条
page|integer|选填|第几页的数据
community_identifier|string|必填|社区唯一编号
