### ISSUE TITLE
房屋列表返回数据有误

### ISSUE THREAD

**Issue by KKMAMi** [wjdh-platform/wjdh-platform-api-document#19]
前端页面加上了切换小区，请求参数也携带了小区标识，但是返回数据还是不对

![image](https://user-images.githubusercontent.com/37092331/103966699-5a32ee00-519b-11eb-8b55-a37158f4a24f.png)
![image](https://user-images.githubusercontent.com/37092331/103966714-61f29280-519b-11eb-876b-14585e85860d.png)

**Comment by KKMAMi** [comment]
@TonyHappyStyle

**Comment by TonyHappyStyle** [comment]
未更新代码导致。现已更新，请重试。
