### ISSUE TITLE
新版后台测试

### ISSUE THREAD

**Issue by KKMAMi** [wjdh-platform/wjdh-platform-api-document#22]
公告通知新增公告不能选择小区

![image](https://user-images.githubusercontent.com/37092331/105432050-ce888980-5c91-11eb-87bf-0970a85c3b59.png)

**Comment by KKMAMi** [comment]
@TonyHappyStyle

**Comment by TonyHappyStyle** [comment]
应该是因为没有使用社区管理员账号
